export interface Todo {
  id: string
  description: string
  date: string
  completed: boolean
}

export const todos: Todo[] = [
  {
    id: '1',
    description: 'Quarterly planning meeting',
    date: '2025-04-01',
    completed: false,
  },
  {
    id: '2',
    description: 'Review Q1 performance',
    date: '2025-04-01',
    completed: false,
  },
  {
    id: '3',
    description: 'Update project roadmap',
    date: '2025-04-01',
    completed: false,
  },
  {
    id: '4',
    description: 'Team standup',
    date: '2025-04-02',
    completed: false,
  },
  {
    id: '5',
    description: 'Client presentation preparation',
    date: '2025-04-02',
    completed: false,
  },
  {
    id: '6',
    description: 'Code review session',
    date: '2025-04-03',
    completed: false,
  },
  {
    id: '7',
    description: 'Update documentation',
    date: '2025-04-03',
    completed: false,
  },
  {
    id: '8',
    description: 'Team lunch',
    date: '2025-04-03',
    completed: false,
  },
  {
    id: '9',
    description: 'Weekly retrospective',
    date: '2025-04-04',
    completed: false,
  },
  {
    id: '10',
    description: 'Deploy new features',
    date: '2025-04-04',
    completed: false,
  },
  {
    id: '11',
    description: 'Weekend project planning',
    date: '2025-04-05',
    completed: false,
  },
  {
    id: '12',
    description: 'Review pull requests',
    date: '2025-04-05',
    completed: false,
  },
  {
    id: '13',
    description: 'Personal development time',
    date: '2025-04-06',
    completed: false,
  },
  {
    id: '14',
    description: 'Read technical articles',
    date: '2025-04-06',
    completed: false,
  },
  {
    id: '15',
    description: 'Prepare for the week ahead',
    date: '2025-04-06',
    completed: false,
  },
  {
    id: '16',
    description: 'Weekly planning meeting',
    date: '2025-04-07',
    completed: false,
  },
  {
    id: '17',
    description: 'Update task board',
    date: '2025-04-07',
    completed: false,
  },
  {
    id: '18',
    description: 'API integration work',
    date: '2025-04-08',
    completed: false,
  },
  {
    id: '19',
    description: 'Debug production issue',
    date: '2025-04-08',
    completed: false,
  },
  {
    id: '20',
    description: 'Team sync-up',
    date: '2025-04-08',
    completed: false,
  },
  {
    id: '21',
    description: 'UX review meeting',
    date: '2025-04-09',
    completed: false,
  },
  {
    id: '22',
    description: 'Refactor authentication module',
    date: '2025-04-09',
    completed: false,
  },
  {
    id: '23',
    description: 'Performance optimization',
    date: '2025-04-10',
    completed: false,
  },
  {
    id: '24',
    description: 'Write unit tests',
    date: '2025-04-10',
    completed: false,
  },
  {
    id: '25',
    description: 'Stakeholder update',
    date: '2025-04-10',
    completed: false,
  },
  {
    id: '26',
    description: 'End-of-week review',
    date: '2025-04-11',
    completed: false,
  },
  {
    id: '27',
    description: 'Team happy hour',
    date: '2025-04-11',
    completed: false,
  },
  {
    id: '28',
    description: 'Weekend code sprint',
    date: '2025-04-12',
    completed: false,
  },
  {
    id: '29',
    description: 'Documentation update',
    date: '2025-04-12',
    completed: false,
  },
  {
    id: '30',
    description: 'Review upcoming sprint',
    date: '2025-04-13',
    completed: false,
  },
  {
    id: '31',
    description: 'Prepare demo for Monday',
    date: '2025-04-13',
    completed: false,
  },
  {
    id: '32',
    description: 'Research new technologies',
    date: '2025-04-13',
    completed: false,
  },
  {
    id: '33',
    description: 'Sprint planning',
    date: '2025-04-14',
    completed: false,
  },
  {
    id: '34',
    description: 'Product demo',
    date: '2025-04-14',
    completed: false,
  },
  {
    id: '35',
    description: 'Tax deadline reminder',
    date: '2025-04-15',
    completed: false,
  },
  {
    id: '36',
    description: 'Implement new feature',
    date: '2025-04-15',
    completed: false,
  },
  {
    id: '37',
    description: 'Code review',
    date: '2025-04-15',
    completed: false,
  },
  {
    id: '38',
    description: 'Mid-sprint check-in',
    date: '2025-04-16',
    completed: true,
  },
  {
    id: '39',
    description: 'Refine backlog',
    date: '2025-04-16',
    completed: false,
  },
  {
    id: '40',
    description: 'Security audit',
    date: '2025-04-17',
    completed: false,
  },
  {
    id: '41',
    description: 'Update dependencies',
    date: '2025-04-17',
    completed: false,
  },
  {
    id: '42',
    description: 'Team knowledge sharing',
    date: '2025-04-17',
    completed: false,
  },
  {
    id: '43',
    description: 'Release planning',
    date: '2025-04-18',
    completed: false,
  },
  {
    id: '44',
    description: 'QA testing',
    date: '2025-04-18',
    completed: false,
  },
  {
    id: '45',
    description: 'Weekend bug fixing',
    date: '2025-04-19',
    completed: false,
  },
  {
    id: '46',
    description: 'Prepare release notes',
    date: '2025-04-19',
    completed: false,
  },
  {
    id: '47',
    description: 'Final release preparations',
    date: '2025-04-20',
    completed: false,
  },
  {
    id: '48',
    description: 'System testing',
    date: '2025-04-20',
    completed: false,
  },
  {
    id: '49',
    description: 'Update user documentation',
    date: '2025-04-20',
    completed: false,
  },
  {
    id: '50',
    description: 'Product release',
    date: '2025-04-21',
    completed: false,
  },
  {
    id: '51',
    description: 'Monitor deployment',
    date: '2025-04-21',
    completed: false,
  },
  {
    id: '52',
    description: 'Earth Day event',
    date: '2025-04-22',
    completed: false,
  },
  {
    id: '53',
    description: 'Post-release bug fixes',
    date: '2025-04-22',
    completed: false,
  },
  {
    id: '54',
    description: 'Start planning next sprint',
    date: '2025-04-22',
    completed: false,
  },
  {
    id: '55',
    description: 'Customer feedback review',
    date: '2025-04-23',
    completed: false,
  },
  {
    id: '56',
    description: 'Backlog grooming',
    date: '2025-04-23',
    completed: false,
  },
  {
    id: '57',
    description: 'Architecture planning',
    date: '2025-04-24',
    completed: false,
  },
  {
    id: '58',
    description: 'Technical debt discussion',
    date: '2025-04-24',
    completed: false,
  },
  {
    id: '59',
    description: 'Team retrospective',
    date: '2025-04-24',
    completed: false,
  },
  {
    id: '60',
    description: 'End of sprint',
    date: '2025-04-25',
    completed: false,
  },
  {
    id: '61',
    description: 'Demo preparation',
    date: '2025-04-25',
    completed: false,
  },
  {
    id: '62',
    description: 'Weekend learning session',
    date: '2025-04-26',
    completed: false,
  },
  {
    id: '63',
    description: 'Review industry trends',
    date: '2025-04-26',
    completed: false,
  },
  {
    id: '64',
    description: 'Prepare for next sprint',
    date: '2025-04-27',
    completed: false,
  },
  {
    id: '65',
    description: 'Review quarterly goals',
    date: '2025-04-27',
    completed: false,
  },
  {
    id: '66',
    description: 'Update personal development plan',
    date: '2025-04-27',
    completed: false,
  },
  {
    id: '67',
    description: 'New sprint kickoff',
    date: '2025-04-28',
    completed: false,
  },
  {
    id: '68',
    description: 'Sprint planning meeting',
    date: '2025-04-28',
    completed: false,
  },
  {
    id: '69',
    description: 'Start implementing new features',
    date: '2025-04-29',
    completed: false,
  },
  {
    id: '70',
    description: 'Team standup',
    date: '2025-04-29',
    completed: false,
  },
  {
    id: '71',
    description: 'Code review session',
    date: '2025-04-29',
    completed: false,
  },
  {
    id: '72',
    description: 'Month-end review',
    date: '2025-04-30',
    completed: false,
  },
  {
    id: '73',
    description: 'Prepare monthly report',
    date: '2025-04-30',
    completed: false,
  },
]
